# Generated by Django 5.1.7 on 2025-03-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='metodos_de_pago',
            field=models.JSONField(default=list),
        ),
    ]
