# Generated by Django 5.1.7 on 2025-04-17 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_metodos_de_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('numero_paginas', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=100)),
                ('issn', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('imagen', models.URLField(blank=True)),
                ('destacado', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('agotado', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='api.libro')),
            ],
        ),
    ]
