# Generated by Django 5.1.7 on 2025-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_pedido_fecha_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='recibir_noticias',
            field=models.BooleanField(default=False),
        ),
    ]
