# Generated by Django 5.1.7 on 2025-06-03 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cliente_recibir_noticias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='cerrado',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
