# Generated by Django 5.1.7 on 2025-06-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_mensaje_asunto_remove_mensaje_cerrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('EN PREPARACION', 'En preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='EN PREPARACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestamensaje',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.administrador'),
        ),
    ]
